### ISSUE TITLE
No sort order on domains

### ISSUE THREAD

**Issue by andysh-uk** [linode/manager#6550] opened 2020-06-17 13:45 UTC
Thanks for the near-realtime updates to your DNS service; I've now migrated my 10-ish zones to your service and can save myself a few quid a month 😄 

One slight gripe - the domain list isn't sorted when you first enter the screen (or it seems to be sorted by the order in which the domains were created.)

If you then click the Domain Name column to sort it, it sorts by name descending (this seems to be a common theme amongst sortable grids in the Manager; whereas generally speaking, when you sort a previously unsorted column, it would sort in ascending order first. If you want it sorted descending, you click it again.)

Could you please sort the domain list by domain name ascending by default, like the Linodes and Volumes lists are?

**Comment by johnwcallahan** [comment] 2020-06-17 21:34
I'm glad the DNS updates are working out for you!

Thanks for reporting the issue with the sorting of the Domains table. It appears this was a recent regression. I just opened https://github.com/linode/manager/pull/6552 which fixes it.

I see the issue you're describing with the default sort order. This one's a bit trickier; looks like our component that handles ordering only keeps track of _one_ order ("asc" or "desc") which is used in all columns. This is leading to the default sorting issue you mentioned as well as some other inconsistent behavior. I've opened an internal bug ticket for us to work this out.

**Comment by andysh-uk** [comment] 2020-06-17 21:42
Thanks for sorting so quickly!

**Comment by johnwcallahan** [comment] 2020-06-30 17:22
Hey @andysh-uk, the fix for this was just released. Check out the [release notes for v1.13.0](https://github.com/linode/manager/releases/tag/linode-manager%40v1.13.0) for the full set of changes.

**Closed by johnwcallahan** 2020-06-30 17:22 UTC

**Comment by andysh-uk** [comment] 2020-06-30 18:25
Looking good, such a small change makes a world of difference.

Thanks again @johnwcallahan !
