### ISSUE TITLE
Implement IP address delete confirmation modal

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#90] opened 2016-06-08 21:21 UTC

**Comment by eatonphil** [comment] 2016-06-08 21:22
![screen shot 2016-06-08 at 5 22 11 pm](https://cloud.githubusercontent.com/assets/3925912/15911354/8ffe16f8-2d9d-11e6-926c-5e933814cbb0.png)

**Comment by na3d** [comment] 2017-04-07 20:51
Duplicate of #258

**Closed** 2017-04-07 20:51 UTC
Labels: Basic UI, Networking, Wire up to API
