### ISSUE TITLE
NodeBalancers page shows "Add a zone" when there are no NodeBalancers

### ISSUE THREAD

**Issue by Dorthu** [linode/manager#1427] opened 2017-03-21 13:32 UTC
<img width="1169" alt="screen shot 2017-03-21 at 9 29 07 am" src="https://cloud.githubusercontent.com/assets/7172953/24149542/49ed2930-0e19-11e7-91df-5f2209a4b29e.png">

**Comment by phuegel** [comment] 2017-03-21 15:22
Two feedback items from this UI:

1. Should "mute" or gray out **[+ Add a NodeBalancer]** button if the prerequisite is to _Add a Zone_ first.
2. Give context to the enduser on what NodeBalancer Zone is or used for.

**Comment by eatonphil** [comment] 2017-03-21 15:23
This is a duplicate of https://github.com/linode/manager/issues/1347, closing.

**Closed by eatonphil** 2017-03-21 15:23 UTC
