### ISSUE TITLE
Object storage, display size

### ISSUE THREAD

**Issue by robo2bobo** [linode/manager#6360] opened 2020-04-29 17:32 UTC
Hello,

I believe that the new Object Storage page is missing a "current size" counter per bucket, because as it is, I can't see how much space I'm using.

In addition, it would be nice if directories also displayed their size, right now only files show their size.

Thank you.

**Comment by kanongil** [comment] 2020-06-04 13:04
I am considering using the object storage product, but I find it concerning that there doesn't appear to be a way for me to see the total amount stored. Especially considering this is a billable metric.

**Comment by johnwcallahan** [comment] 2020-06-04 16:09
Hi @robo2bobo, I'm going to close this as a duplicate of https://github.com/linode/manager/issues/6256; feel free to pick the conversation up there. I've taken note of your request, though I don't have any details to offer in terms of a timeline yet.

**Closed by johnwcallahan** 2020-06-04 16:09 UTC
