### ISSUE TITLE
Fix Rescue defaults

### ISSUE THREAD

**Issue by na3d** [linode/manager#2306] opened 2017-07-18 15:05 UTC
"I don't know if it's intentional or not, but the linode rescue screen
used to prepopulate /dev/sda with the main disk, and the swap in the
/sdb, but now defaults to "none" for each disk."

**Comment by eatonphil** [comment] 2017-07-18 15:30
Thanks! This is a duplicate of #1995.

**Closed by eatonphil** 2017-07-18 15:30 UTC
Labels: bug
